/**
 * Common-word dictionary for QWERTY (romanized) Hindi/Urdu transliteration.
 *
 * The rule engines handle arbitrary words, but everyday Hinglish / Roman Urdu
 * typing is full of words where naive letter-rules pick the wrong vowel length
 * ("karna" → करना not कर्ना, "khana" → खाना not खन, "pyar" → प्यार not पयार).
 * This table pins the ~300 most frequent tokens so typical sentences come out
 * correct on the first pass. Both scripts get their own rendering of the same
 * roman headword; multi-word phrases (checked as bigrams first) are included
 * with a "_" joined key.
 */

export interface DictEntry {
  hi: string;
  ur: string;
}

export const COMMON_WORDS: Record<string, DictEntry> = {
  // ── core grammar ──────────────────────────────────────────────────────────
  kya: { hi: "क्या", ur: "کیا" },
  hai: { hi: "है", ur: "ہے" },
  hain: { hi: "हैं", ur: "ہیں" },
  hun: { hi: "हूँ", ur: "ہوں" },
  hoon: { hi: "हूँ", ur: "ہوں" },
  hu: { hi: "हूँ", ur: "ہوں" },
  tha: { hi: "था", ur: "تھا" },
  thi: { hi: "थी", ur: "تھی" },
  the: { hi: "थे", ur: "تھے" },
  hoga: { hi: "होगा", ur: "ہوگا" },
  hogi: { hi: "होगी", ur: "ہوگی" },
  honge: { hi: "होंगे", ur: "ہوںگے" },
  raha: { hi: "रहा", ur: "رہا" },
  rahi: { hi: "रही", ur: "رہی" },
  rahe: { hi: "रहे", ur: "رہے" },
  nahi: { hi: "नहीं", ur: "نہیں" },
  nahin: { hi: "नहीं", ur: "نہیں" },
  na: { hi: "ना", ur: "نا" },
  mat: { hi: "मत", ur: "مت" },
  main: { hi: "मैं", ur: "میں" },
  mein: { hi: "में", ur: "میں" },
  mujhe: { hi: "मुझे", ur: "مجھے" },
  mujhko: { hi: "मुझको", ur: "مجھ کو" },
  mera: { hi: "मेरा", ur: "میرا" },
  meri: { hi: "मेरी", ur: "میری" },
  mere: { hi: "मेरे", ur: "میرے" },
  humara: { hi: "हमारा", ur: "ہمارا" },
  hamara: { hi: "हमारा", ur: "ہمارا" },
  humari: { hi: "हमारी", ur: "ہماری" },
  hamari: { hi: "हमारी", ur: "ہماری" },
  humare: { hi: "हमारे", ur: "ہمارے" },
  hamare: { hi: "हमारे", ur: "ہمارے" },
  hum: { hi: "हम", ur: "ہم" },
  ham: { hi: "हम", ur: "ہم" },
  humein: { hi: "हमें", ur: "ہمیں" },
  tere: { hi: "तेरे", ur: "تیرے" },
  tera: { hi: "तेरा", ur: "تیرا" },
  teri: { hi: "तेरी", ur: "تیری" },
  tumhara: { hi: "तुम्हारा", ur: "تمہارا" },
  tumhari: { hi: "तुम्हारी", ur: "تمہاری" },
  tumhare: { hi: "तुम्हारे", ur: "تمہارے" },
  tumse: { hi: "तुमसे", ur: "تم سے" },
  tum: { hi: "तुम", ur: "تم" },
  tumhe: { hi: "तुम्हें", ur: "تمہیں" },
  tu: { hi: "तू", ur: "تو" },
  aap: { hi: "आप", ur: "آپ" },
  aapka: { hi: "आपका", ur: "آپ کا" },
  aapki: { hi: "आपकी", ur: "آپ کی" },
  aapke: { hi: "आपके", ur: "آپ کے" },
  uska: { hi: "उसका", ur: "اس کا" },
  uski: { hi: "उसकी", ur: "اس کی" },
  uske: { hi: "उसके", ur: "اس کے" },
  usko: { hi: "उसको", ur: "اس کو" },
  isko: { hi: "इसको", ur: "اس کو" },
  iska: { hi: "इसका", ur: "اس کا" },
  iski: { hi: "इसकी", ur: "اس کی" },
  inka: { hi: "इनका", ur: "ان کا" },
  ye: { hi: "ये", ur: "یہ" },
  yeh: { hi: "यह", ur: "یہ" },
  vo: { hi: "वो", ur: "وہ" },
  woh: { hi: "वह", ur: "وہ" },
  wahan: { hi: "वहाँ", ur: "وہاں" },
  yahan: { hi: "यहाँ", ur: "یہاں" },
  ka: { hi: "का", ur: "کا" },
  ki: { hi: "की", ur: "کی" },
  ke: { hi: "के", ur: "کے" },
  ko: { hi: "को", ur: "کو" },
  se: { hi: "से", ur: "سے" },
  par: { hi: "पर", ur: "پر" },
  pe: { hi: "पे", ur: "پے" },
  tak: { hi: "तक", ur: "تک" },
  liye: { hi: "लिए", ur: "لیے" },
  bhi: { hi: "भी", ur: "بھی" },
  hi: { hi: "ही", ur: "ہی" },
  to: { hi: "तो", ur: "تو" },
  toh: { hi: "तो", ur: "تو" },
  aur: { hi: "और", ur: "اور" },
  ya: { hi: "या", ur: "یا" },
  lekin: { hi: "लेकिन", ur: "لیکن" },
  magar: { hi: "मगर", ur: "مگر" },
  kyunki: { hi: "क्योंकि", ur: "کیونکہ" },
  isliye: { hi: "इसलिए", ur: "اس لیے" },
  warna: { hi: "वरना", ur: "ورنہ" },
  phir: { hi: "फिर", ur: "پھر" },
  jab: { hi: "जब", ur: "جب" },
  tab: { hi: "तब", ur: "تب" },
  jabki: { hi: "जबकि", ur: "جبکہ" },

  // ── question words ───────────────────────────────────────────────────────
  kyun: { hi: "क्यों", ur: "کیوں" },
  kyu: { hi: "क्यों", ur: "کیوں" },
  kaise: { hi: "कैसे", ur: "کیسے" },
  kaisa: { hi: "कैसा", ur: "کیسا" },
  kaisi: { hi: "कैसी", ur: "کیسی" },
  kitna: { hi: "कितना", ur: "کتنا" },
  kitni: { hi: "कितनी", ur: "کتنی" },
  kab: { hi: "कब", ur: "کب" },
  kahan: { hi: "कहाँ", ur: "کہاں" },
  kaha: { hi: "कहाँ", ur: "کہاں" },
  kaun: { hi: "कौन", ur: "کون" },
  kaunsa: { hi: "कौन सा", ur: "کون سا" },
  kisko: { hi: "किसको", ur: "کس کو" },
  kiska: { hi: "किसका", ur: "کس کا" },

  // ── time ─────────────────────────────────────────────────────────────────
  aaj: { hi: "आज", ur: "آج" },
  kal: { hi: "कल", ur: "کل" },
  ab: { hi: "अब", ur: "اب" },
  abhi: { hi: "अभी", ur: "ابھی" },
  subah: { hi: "सुबह", ur: "صبح" },
  shaam: { hi: "शाम", ur: "شام" },
  sham: { hi: "शाम", ur: "شام" },
  dopahar: { hi: "दोपहर", ur: "دوپہر" },
  raat: { hi: "रात", ur: "رات" },
  din: { hi: "दिन", ur: "دن" },
  saal: { hi: "साल", ur: "سال" },
  mahine: { hi: "महीने", ur: "مہینے" },
  hafte: { hi: "हफ़्ते", ur: "ہفتے" },
  ghante: { hi: "घंटे", ur: "گھنٹے" },
  der: { hi: "देर", ur: "دیر" },
  jaldi: { hi: "जल्दी", ur: "جلدی" },

  // ── family & people ──────────────────────────────────────────────────────
  maa: { hi: "माँ", ur: "ماں" },
  ammi: { hi: "अम्मी", ur: "امی" },
  mummy: { hi: "मम्मी", ur: "ممی" },
  papa: { hi: "पापा", ur: "پاپا" },
  abba: { hi: "अब्बा", ur: "ابا" },
  bhai: { hi: "भाई", ur: "بھائی" },
  behen: { hi: "बहन", ur: "بہن" },
  beta: { hi: "बेटा", ur: "بیٹا" },
  beti: { hi: "बेटी", ur: "بیٹی" },
  dada: { hi: "दादा", ur: "دادا" },
  dadi: { hi: "दादी", ur: "دادی" },
  nana: { hi: "नाना", ur: "نانا" },
  nani: { hi: "नानी", ur: "نانی" },
  chacha: { hi: "चाचा", ur: "چچا" },
  chachi: { hi: "चाची", ur: "چچی" },
  dost: { hi: "दोस्त", ur: "دوست" },
  yaar: { hi: "यार", ur: "یار" },
  aadmi: { hi: "आदमी", ur: "آدمی" },
  aurat: { hi: "औरत", ur: "عورت" },
  ladka: { hi: "लड़का", ur: "لڑکا" },
  ladki: { hi: "लड़की", ur: "لڑکی" },
  larka: { hi: "लड़का", ur: "لڑکا" },
  larki: { hi: "लड़की", ur: "لڑکی" },
  log: { hi: "लोग", ur: "لوگ" },
  bacche: { hi: "बच्चे", ur: "بچے" },
  bachche: { hi: "बच्चे", ur: "بچے" },
  parivaar: { hi: "परिवार", ur: "خاندان" },
  rishta: { hi: "रिश्ता", ur: "رشتہ" },

  // ── common verbs ─────────────────────────────────────────────────────────
  karna: { hi: "करना", ur: "کرنا" },
  kar: { hi: "कर", ur: "کر" },
  karo: { hi: "करो", ur: "کرو" },
  karta: { hi: "करता", ur: "کرتا" },
  karti: { hi: "करती", ur: "کرتی" },
  karte: { hi: "करते", ur: "کرتے" },
  kiya: { hi: "किया", ur: "کیا" },
  hone: { hi: "होने", ur: "ہونے" },
  hona: { hi: "होना", ur: "ہونا" },
  ho: { hi: "हो", ur: "ہو" },
  hua: { hi: "हुआ", ur: "ہوا" },
  hui: { hi: "हुई", ur: "ہوئی" },
  jana: { hi: "जाना", ur: "جانا" },
  jaana: { hi: "जाना", ur: "جانا" },
  ja: { hi: "जा", ur: "جا" },
  jao: { hi: "जाओ", ur: "جاؤ" },
  gaya: { hi: "गया", ur: "گیا" },
  gayi: { hi: "गई", ur: "گئی" },
  ana: { hi: "आना", ur: "آنا" },
  aana: { hi: "आना", ur: "آنا" },
  aa: { hi: "आ", ur: "آ" },
  aao: { hi: "आओ", ur: "آؤ" },
  aaya: { hi: "आया", ur: "آیا" },
  aayi: { hi: "आई", ur: "آئی" },
  dena: { hi: "देना", ur: "دینا" },
  de: { hi: "दे", ur: "دے" },
  do: { hi: "दो", ur: "دو" },
  diya: { hi: "दिया", ur: "دیا" },
  lena: { hi: "लेना", ur: "لینا" },
  le: { hi: "ले", ur: "لے" },
  liya: { hi: "लिया", ur: "لیا" },
  milna: { hi: "मिलना", ur: "ملنا" },
  mila: { hi: "मिला", ur: "ملا" },
  milega: { hi: "मिलेगा", ur: "ملے گا" },
  bolna: { hi: "बोलना", ur: "بولنا" },
  bolo: { hi: "बोलो", ur: "بولو" },
  bol: { hi: "बोल", ur: "بول" },
  bola: { hi: "बोला", ur: "بولا" },
  kaho: { hi: "कहो", ur: "کہو" },
  batao: { hi: "बताओ", ur: "بتاؤ" },
  batana: { hi: "बताना", ur: "بتانا" },
  sunna: { hi: "सुनना", ur: "سننا" },
  suno: { hi: "सुनो", ur: "سنو" },
  sun: { hi: "सुन", ur: "سن" },
  suna: { hi: "सुना", ur: "سنا" },
  dekhna: { hi: "देखना", ur: "دیکھنا" },
  dekho: { hi: "देखो", ur: "دیکھو" },
  dekh: { hi: "देख", ur: "دیکھ" },
  dekha: { hi: "देखा", ur: "دیکھا" },
  parhna: { hi: "पढ़ना", ur: "پڑھنا" },
  padhna: { hi: "पढ़ना", ur: "پڑھنا" },
  likhna: { hi: "लिखना", ur: "لکھنا" },
  rehna: { hi: "रहना", ur: "رہنا" },
  samajhna: { hi: "समझना", ur: "سمجھنا" },
  chalna: { hi: "चलना", ur: "چلنا" },
  chalo: { hi: "चलो", ur: "چلو" },
  chal: { hi: "चल", ur: "چل" },
  ruk: { hi: "रुक", ur: "رک" },
  ruko: { hi: "रुको", ur: "رکو" },
  khana: { hi: "खाना", ur: "کھانا" },
  khao: { hi: "खाओ", ur: "کھاؤ" },
  khaya: { hi: "खाया", ur: "کھایا" },
  peena: { hi: "पीना", ur: "پینا" },
  pina: { hi: "पीना", ur: "پینا" },
  sona: { hi: "सोना", ur: "سونا" },
  sone: { hi: "सोने", ur: "سونے" },
  uthna: { hi: "उठना", ur: "اٹھنا" },
  baithna: { hi: "बैठना", ur: "بیٹھنا" },
  hasna: { hi: "हँसना", ur: "ہنسنا" },
  rona: { hi: "रोना", ur: "رونا" },
  khelna: { hi: "खेलना", ur: "کھیلنا" },
  banana: { hi: "बनाना", ur: "بنانا" },
  lagna: { hi: "लगना", ur: "لگنا" },
  chahna: { hi: "चाहना", ur: "چاہنا" },
  chahta: { hi: "चाहता", ur: "چاہتا" },
  chahti: { hi: "चाहती", ur: "چاہتی" },
  chahte: { hi: "चाहते", ur: "چاہتے" },
  sakte: { hi: "सकते", ur: "سکتے" },
  sakti: { hi: "सकती", ur: "سکتی" },
  sakta: { hi: "सकता", ur: "سکتا" },
  paana: { hi: "पाना", ur: "پانا" },
  pana: { hi: "पाना", ur: "پانا" },
  chhodna: { hi: "छोड़ना", ur: "چھوڑنا" },

  // ── adjectives & adverbs ─────────────────────────────────────────────────
  accha: { hi: "अच्छा", ur: "اچھا" },
  achha: { hi: "अच्छा", ur: "اچھا" },
  achchha: { hi: "अच्छा", ur: "اچھا" },
  acchi: { hi: "अच्छी", ur: "اچھی" },
  bura: { hi: "बुरा", ur: "برا" },
  bada: { hi: "बड़ा", ur: "بڑا" },
  chhota: { hi: "छोटा", ur: "چھوٹا" },
  naya: { hi: "नया", ur: "نیا" },
  nayi: { hi: "नई", ur: "نئی" },
  purana: { hi: "पुराना", ur: "پرانا" },
  sundar: { hi: "सुंदर", ur: "خوبصورت" },
  garam: { hi: "गरम", ur: "گرم" },
  thanda: { hi: "ठंडा", ur: "ٹھنڈا" },
  khush: { hi: "खुश", ur: "خوش" },
  udaas: { hi: "उदास", ur: "اداس" },
  gussa: { hi: "गुस्सा", ur: "غصہ" },
  saccha: { hi: "सच्चा", ur: "سچا" },
  sach: { hi: "सच", ur: "سچ" },
  jhoot: { hi: "झूठ", ur: "جھوٹ" },
  saaf: { hi: "साफ़", ur: "صاف" },
  ganda: { hi: "गंदा", ur: "گندا" },
  tez: { hi: "तेज़", ur: "تیز" },
  dheere: { hi: "धीरे", ur: "دھیرے" },
  seedha: { hi: "सीधा", ur: "سیدھا" },
  khali: { hi: "खाली", ur: "خالی" },
  bahut: { hi: "बहुत", ur: "بہت" },
  bohat: { hi: "बहुत", ur: "بہت" },
  zyada: { hi: "ज़्यादा", ur: "زیادہ" },
  thoda: { hi: "थोड़ा", ur: "تھوڑا" },
  thori: { hi: "थोड़ी", ur: "تھوڑی" },
  kaafi: { hi: "काफ़ी", ur: "کافی" },
  itna: { hi: "इतना", ur: "اتنا" },
  utna: { hi: "उतना", ur: "اتنا" },
  sabse: { hi: "सबसे", ur: "سب سے" },
  badhiya: { hi: "बढ़िया", ur: "بڑھیا" },
  mast: { hi: "मस्त", ur: "مست" },
  zabardast: { hi: "ज़बरदस्त", ur: "زبردست" },
  kamaal: { hi: "कमाल", ur: "کمال" },
  theek: { hi: "ठीक", ur: "ٹھیک" },
  haan: { hi: "हाँ", ur: "ہاں" },
  haa: { hi: "हाँ", ur: "ہاں" },
  sahi: { hi: "सही", ur: "صحیح" },
  galat: { hi: "ग़लत", ur: "غلط" },

  // ── common nouns ─────────────────────────────────────────────────────────
  kaam: { hi: "काम", ur: "کام" },
  ghar: { hi: "घर", ur: "گھر" },
  kamra: { hi: "कमरा", ur: "کمرہ" },
  dil: { hi: "दिल", ur: "دل" },
  pyar: { hi: "प्यार", ur: "پیار" },
  pyaar: { hi: "प्यार", ur: "پیار" },
  mohabbat: { hi: "मोहब्बत", ur: "محبت" },
  paani: { hi: "पानी", ur: "پانی" },
  pani: { hi: "पानी", ur: "پانی" },
  roti: { hi: "रोटी", ur: "روٹی" },
  namak: { hi: "नमक", ur: "نمک" },
  dudh: { hi: "दूध", ur: "دودھ" },
  chai: { hi: "चाय", ur: "چائے" },
  chay: { hi: "चाय", ur: "چائے" },
  darwaza: { hi: "दरवाज़ा", ur: "دروازہ" },
  sadak: { hi: "सड़क", ur: "سڑک" },
  shehar: { hi: "शहर", ur: "شہر" },
  gaon: { hi: "गाँव", ur: "گاؤں" },
  desh: { hi: "देश", ur: "ملک" },
  mulk: { hi: "मुल्क", ur: "ملک" },
  duniya: { hi: "दुनिया", ur: "دنیا" },
  zindagi: { hi: "ज़िंदगी", ur: "زندگی" },
  maut: { hi: "मौत", ur: "موت" },
  dimaag: { hi: "दिमाग़", ur: "دماغ" },
  dimag: { hi: "दिमाग़", ur: "دماغ" },
  haath: { hi: "हाथ", ur: "ہاتھ" },
  pair: { hi: "पैर", ur: "پیر" },
  aankh: { hi: "आँख", ur: "آنکھ" },
  kaan: { hi: "कान", ur: "کان" },
  naak: { hi: "नाक", ur: "ناک" },
  sir: { hi: "सिर", ur: "سر" },
  pet: { hi: "पेट", ur: "پیٹ" },
  saans: { hi: "साँस", ur: "سانس" },
  paisa: { hi: "पैसा", ur: "پیسہ" },
  paise: { hi: "पैसे", ur: "پیسے" },
  baat: { hi: "बात", ur: "بات" },
  batein: { hi: "बातें", ur: "باتیں" },
  sawal: { hi: "सवाल", ur: "سوال" },
  jawab: { hi: "जवाब", ur: "جواب" },
  waada: { hi: "वादा", ur: "وعدہ" },
  khushi: { hi: "खुशी", ur: "خوشی" },
  dukh: { hi: "दुख", ur: "دکھ" },
  dard: { hi: "दर्द", ur: "درد" },
  rasta: { hi: "रास्ता", ur: "راستہ" },
  raasta: { hi: "रास्ता", ur: "راستہ" },
  manzil: { hi: "मंज़िल", ur: "منزل" },
  sapna: { hi: "सपना", ur: "سپنہ" },
  khwab: { hi: "ख़्वाब", ur: "خواب" },
  mauka: { hi: "मौका", ur: "موقع" },
  jagah: { hi: "जगह", ur: "جگہ" },
  tareeka: { hi: "तरीक़ा", ur: "طریقہ" },
  tarika: { hi: "तरीक़ा", ur: "طریقہ" },
  wajah: { hi: "वजह", ur: "وجہ" },
  fayda: { hi: "फ़ायदा", ur: "فائدہ" },
  nuksan: { hi: "नुक़सान", ur: "نقصان" },
  izzat: { hi: "इज़्ज़त", ur: "عزت" },
  sharam: { hi: "शरम", ur: "شرم" },
  dar: { hi: "डर", ur: "ڈر" },
  himmat: { hi: "हिम्मत", ur: "ہمت" },
  zor: { hi: "ज़ोर", ur: "زور" },
  taqat: { hi: "ताक़त", ur: "طاقت" },

  // ── numbers ──────────────────────────────────────────────────────────────
  ek: { hi: "एक", ur: "ایک" },
  teen: { hi: "तीन", ur: "تین" },
  char: { hi: "चार", ur: "چار" },
  chaar: { hi: "चार", ur: "چار" },
  panch: { hi: "पाँच", ur: "پانچ" },
  chhe: { hi: "छह", ur: "چھ" },
  saat: { hi: "सात", ur: "سات" },
  aath: { hi: "आठ", ur: "آٹھ" },
  nau: { hi: "नौ", ur: "نو" },
  das: { hi: "दस", ur: "دس" },
  sau: { hi: "सौ", ur: "سو" },
  hazaar: { hi: "हज़ार", ur: "ہزار" },
  hazar: { hi: "हज़ार", ur: "ہزار" },
  lakh: { hi: "लाख", ur: "لاکھ" },
  koi: { hi: "कोई", ur: "کوئی" },
  kuch: { hi: "कुछ", ur: "کچھ" },
  sab: { hi: "सब", ur: "سب" },

  // ── greetings & phrases ──────────────────────────────────────────────────
  namaste: { hi: "नमस्ते", ur: "سلام" },
  salaam: { hi: "सलाम", ur: "سلام" },
  salam: { hi: "सलाम", ur: "سلام" },
  assalamualaikum: { hi: "अस्सलाम अलैकुम", ur: "السلام علیکم" },
  khuda_hafiz: { hi: "ख़ुदा हाफ़िज़", ur: "خدا حافظ" },
  allah_hafiz: { hi: "अल्लाह हाफ़िज़", ur: "اللہ حافظ" },
  shukriya: { hi: "शुक्रिया", ur: "شکریہ" },
  dhanyavaad: { hi: "धन्यवाद", ur: "شکریہ" },
  maaf: { hi: "माफ़", ur: "معاف" },
  kya_haal: { hi: "क्या हाल", ur: "کیا حال" },
  theek_hai: { hi: "ठीक है", ur: "ٹھیک ہے" },
  koi_baat: { hi: "कोई बात", ur: "کوئی بات" },
  koi_baat_nahi: { hi: "कोई बात नहीं", ur: "کوئی بات نہیں" },
  inshallah: { hi: "इन्शाअल्लाह", ur: "انشاءاللہ" },
  mashallah: { hi: "माशाअल्लाह", ur: "ماشاءاللہ" },
  khuda: { hi: "ख़ुदा", ur: "خدا" },
  allah: { hi: "अल्लाह", ur: "اللہ" },

  // ── words that trip the letter rules ─────────────────────────────────────
  ram: { hi: "राम", ur: "رام" },
  krishna: { hi: "कृष्ण", ur: "کرشن" },
  karam: { hi: "करम", ur: "کرم" },
  dharm: { hi: "धर्म", ur: "دھرم" },
  dharma: { hi: "धर्म", ur: "دھرم" },
  mantra: { hi: "मंत्र", ur: "منتر" },
  karma: { hi: "कर्म", ur: "کرم" },
  gyaan: { hi: "ज्ञान", ur: "علم" },
  gyan: { hi: "ज्ञान", ur: "علم" },
  lakshya: { hi: "लक्ष्य", ur: "لکشيا" },
  satya: { hi: "सत्य", ur: "سچائی" },
  chitra: { hi: "चित्र", ur: "تصویر" },
  khel: { hi: "खेल", ur: "کھیل" },
  khelo: { hi: "खेलो", ur: "کھیلو" },
  meetha: { hi: "मीठा", ur: "میٹھا" },
  cheeni: { hi: "चीनी", ur: "چینی" },
  insaan: { hi: "इंसान", ur: "انسان" },
  chunna: { hi: "चुनना", ur: "چننا" },
  panna: { hi: "पन्ना", ur: "پنہ" },
  pakka: { hi: "पक्का", ur: "پکا" },
  aaunga: { hi: "आऊँगा", ur: "آؤں گا" },
  aaungi: { hi: "आऊँगी", ur: "آؤں گی" },
  jaayega: { hi: "जाएगा", ur: "جائے گا" },
  jaayegi: { hi: "जाएगी", ur: "جائے گی" },
  banega: { hi: "बनेगा", ur: "بنے گا" },
  banegi: { hi: "बनेगी", ur: "بنے گی" },
  lagta: { hi: "लगता", ur: "لگتا" },
  lagti: { hi: "लगती", ur: "لگتی" },
  lagte: { hi: "लगते", ur: "لگتے" },
  dikhta: { hi: "दिखता", ur: "دکھتا" },
  dikhti: { hi: "दिखती", ur: "دکھتی" },
  hota: { hi: "होता", ur: "ہوتا" },
  hoti: { hi: "होती", ur: "ہوتی" },
  hote: { hi: "होते", ur: "ہوتے" },
  wala: { hi: "वाला", ur: "والا" },
  wali: { hi: "वाली", ur: "والی" },
  wale: { hi: "वाले", ur: "والے" },
  chahiye: { hi: "चाहिए", ur: "چاہیے" },
  zaroor: { hi: "ज़रूर", ur: "ضرور" },
  zaruri: { hi: "ज़रूरी", ur: "ضروری" },
  skte: { hi: "सकते", ur: "سکتے" },
  krna: { hi: "करना", ur: "کرنا" },
  krdo: { hi: "कर दो", ur: "کر دو" },
  kardo: { hi: "कर दो", ur: "کر دو" },
  kardena: { hi: "कर देना", ur: "کر دینا" },
  sunao: { hi: "सुनाओ", ur: "سناؤ" },
  lagao: { hi: "लगाओ", ur: "لگاؤ" },
  dikhaao: { hi: "दिखाओ", ur: "دکھاؤ" },
  dikha: { hi: "दिखा", ur: "دکھا" },
};

/** Two-word phrases are looked up with a "_" joined key before singles. */
export function bigramKey(a: string, b: string): string {
  return `${a}_${b}`;
}
