// src/lib/merger/benchExport.ts — the REAL-HARDWARE A/B export bench
// (v1.15.2, user directive #3): "since headless Chromium cannot test
// hardware encoding, write a script that builds the Electron app, runs a
// 1080p 60s timeline export using the FFmpeg NVENC path, and then runs the
// exact same timeline using the WebCodecs GPU path on a real Windows
// machine. Compare the wall-clock time and gpuFrameRenderMs telemetry."
//
// This is the renderer side. scripts/ab-export-bench.js (the driver) spawns
// the app with FRAMEFUSE_BENCH=1 + a plan JSON; electron/main.js reads the
// plan, ships the fixture media bytes here over IPC ("bench:run"), and THIS
// module runs the SAME timeline through BOTH engines against fixed output
// paths (no save dialog), then posts the timings back ("bench:result") —
// main writes the results JSON and quits. The driver prints the table.
//
// Fixture timeline (the plan's media, generated by the driver's ffmpeg):
//   [image ×1 with Ken Burns] + [video ×N] = durationSec total, hard cuts
//   (the v5 VIDEO RULE makes video boundaries hard cuts anyway), background
//   music looping at 50%, per-clip audio at 80%. Captions/transitions off —
//   the bench measures the DECODE → COMPOSITE → ENCODE wall, the part both
//   engines share, not per-feature parity.
//
// Bench order: FFmpeg (forced to the plan's encoder, default NVENC) FIRST,
// then the WebCodecs GPU worker — so the GPU run also proves the worker
// spawns inside the real packaged app (workerRuntime telemetry).

import { runExportNativeToPath } from "./native";
import type { AudioTrack, ExportResult, KenBurnsConfig, MediaSegment, VideoSettings } from "./types";

/** One fixture media file shipped from the main process. */
interface BenchMedia {
  name: string;
  kind: "video" | "image" | "audio";
  bytes: ArrayBuffer;
}

/** The bench configuration from the plan JSON. */
interface BenchConfig {
  outputDir: string;
  durationSec: number;
  fps: number;
  resolution: string;
  aspect: string;
  quality: string;
  forceEncoder: string | null;
  captions: boolean;
}

/** The result posted back to main (verbatim JSON on disk). */
interface BenchRunResult {
  engine: "ffmpeg-smart" | "webcodecs-gpu";
  label: string;
  ok: boolean;
  wallMs: number;
  elapsedSec?: number;
  size?: number;
  path?: string;
  framesEncoded?: number;
  encoder?: string;
  gpuFrameRenderMs?: number;
  jsCompositorOverheadMs?: number;
  gpuDecodeWaitMs?: number;
  softwareFallback?: boolean;
  workerRuntime?: string;
  audioSkipped?: boolean;
  error: string | null;
}

interface BenchApi {
  onBenchRun: (cb: (payload: { media: BenchMedia[]; config: BenchConfig }) => void) => () => void;
  benchResult: (payload: unknown) => Promise<unknown>;
  setForceEncoder: (key: string | null) => Promise<unknown>;
  cleanupTemp: () => Promise<unknown>;
  appInfo: () => Promise<{ version?: string; platform?: string }>;
}

function benchApi(): BenchApi | null {
  if (typeof window === "undefined") return null;
  const w = window as Window & { electronAPI?: BenchApi };
  const api = w.electronAPI;
  if (!api || typeof api.onBenchRun !== "function" || typeof api.benchResult !== "function") {
    return null;
  }
  return api;
}

function mimeOf(name: string): string {
  if (name.endsWith(".png")) return "image/png";
  if (name.endsWith(".jpg") || name.endsWith(".jpeg")) return "image/jpeg";
  if (name.endsWith(".wav")) return "audio/wav";
  return "video/mp4";
}

/**
 * Build the bench timeline model — the exact MediaSegment shape page.tsx
 * resolves for a real storyboard (base lane, cumulative positions, per-clip
 * volume, full-window trims, object URLs for every source).
 */
function buildBenchTimeline(media: BenchMedia[], config: BenchConfig): {
  segments: MediaSegment[];
  imageUrls: Record<string, string>;
  audioTrack: AudioTrack | null;
  settings: VideoSettings;
  kenBurns: KenBurnsConfig;
  totalMs: number;
  revoke: () => void;
} {
  const videos = media.filter((m) => m.kind === "video");
  const images = media.filter((m) => m.kind === "image");
  const audio = media.find((m) => m.kind === "audio") ?? null;

  const slots = Math.max(1, videos.length + images.length);
  const clipMs = Math.round((config.durationSec * 1000) / slots);
  const totalMs = clipMs * slots;

  const files = new Map<string, File>();
  const urls = new Map<string, string>();
  for (const m of media) {
    const f = new File([m.bytes], m.name, { type: mimeOf(m.name) });
    files.set(m.name, f);
    urls.set(m.name, URL.createObjectURL(f));
  }

  // Image first (Ken Burns), then the video clips — cumulative timeline.
  const ordered = [...images, ...videos];
  const segments: MediaSegment[] = ordered.map((m, i) => {
    const url = urls.get(m.name) as string;
    const isImage = m.kind === "image";
    return {
      id: `bench-${i}`,
      fileName: m.name,
      file: files.get(m.name),
      kind: "duration" as const,
      startMs: i * clipMs,
      endMs: (i + 1) * clipMs,
      durationMs: clipMs,
      rawStartMs: null,
      rawDurationMs: clipMs,
      rawEndMs: null,
      direction: "in" as const,
      thumbnailUrl: url,
      order: i,
      mediaType: isImage ? ("image" as const) : ("video" as const),
      track: 0,
      volume: 0.8,
      trimInMs: 0,
      sourceDurationMs: isImage ? null : clipMs,
      speed: 1,
      overlayLoop: false,
      chroma: null,
      overlay: null,
    };
  });

  // page.tsx maps EVERY item's object URL under its segment id — videos
  // included (the GPU audio arm fetches clip audio through this map).
  const imageUrls: Record<string, string> = {};
  for (const seg of segments) imageUrls[seg.id] = seg.thumbnailUrl;

  const audioTrack: AudioTrack | null = audio
    ? {
        fileName: audio.name,
        url: urls.get(audio.name) as string,
        durationMs: totalMs,
        sourcePath: null,
      }
    : null;

  const settings: VideoSettings = {
    aspect: (config.aspect as VideoSettings["aspect"]) || "16:9",
    resolution: (config.resolution as VideoSettings["resolution"]) || "1080p",
    bitrateMbps: 8,
    fps: (config.fps === 24 || config.fps === 60 ? config.fps : 30) as VideoSettings["fps"],
    quality: (config.quality as VideoSettings["quality"]) || "social",
  };

  const kenBurns: KenBurnsConfig = {
    enabled: true,
    intensity: 35,
    direction: "in",
    directionPool: ["in", "out", "left", "right", "up", "down"],
  };

  return {
    segments,
    imageUrls,
    audioTrack,
    settings,
    kenBurns,
    totalMs,
    revoke: () => {
      for (const u of urls.values()) URL.revokeObjectURL(u);
    },
  };
}

function runResultOf(
  engine: "ffmpeg-smart" | "webcodecs-gpu",
  label: string,
  wallMs: number,
  res: ExportResult,
): BenchRunResult {
  return {
    engine,
    label,
    ok: true,
    wallMs,
    elapsedSec: res.elapsedSec,
    size: res.size,
    path: res.path,
    framesEncoded: res.framesEncoded,
    encoder: res.encoder,
    ...(res.gpuFrameRenderMs != null ? { gpuFrameRenderMs: res.gpuFrameRenderMs } : {}),
    ...(res.jsCompositorOverheadMs != null
      ? { jsCompositorOverheadMs: res.jsCompositorOverheadMs }
      : {}),
    ...(res.gpuDecodeWaitMs != null ? { gpuDecodeWaitMs: res.gpuDecodeWaitMs } : {}),
    ...(res.softwareFallback != null ? { softwareFallback: res.softwareFallback } : {}),
    ...(res.workerRuntime != null ? { workerRuntime: res.workerRuntime } : {}),
    ...(res.audioSkipped != null ? { audioSkipped: res.audioSkipped } : {}),
    error: null,
  };
}

async function runBench(payload: { media: BenchMedia[]; config: BenchConfig }): Promise<void> {
  const api = benchApi();
  if (!api) return;
  const { media, config } = payload;
  const runs: BenchRunResult[] = [];
  let appVersion = "unknown";
  let platform = "unknown";
  try {
    const info = await api.appInfo();
    appVersion = info?.version ?? appVersion;
    platform = info?.platform ?? platform;
  } catch {
    /* non-fatal — telemetry only */
  }

  const tl = buildBenchTimeline(media, config);
  const ffmpegPath = `${config.outputDir}/bench-ffmpeg.mp4`.replaceAll("\\", "/");
  const gpuPath = `${config.outputDir}/bench-webcodecs.mp4`.replaceAll("\\", "/");

  const progressLogger = (tag: string) => (p: { progress?: number; framesEncoded?: number; totalFrames?: number }) => {
    const pct = p.progress != null ? Math.round(p.progress) : -1;
    if (pct >= 0 && pct % 10 === 0) {
      console.info(
        `[bench:${tag}] ${pct}% (frame ${p.framesEncoded ?? "?"}/${p.totalFrames ?? "?"})`,
      );
    }
  };

  try {
    // ── Run 1: FFmpeg, forced to the plan's encoder (default NVENC). ──────
    // main.js already applied plan.forceEncoder at startup; re-assert here so
    // a manual bench:run through devtools also gets the forced ladder.
    if (config.forceEncoder && config.forceEncoder !== "none") {
      try {
        await api.setForceEncoder(config.forceEncoder);
      } catch {
        /* the startup force in main still applies */
      }
    }
    console.info(
      `[bench] run 1/2: FFmpeg${config.forceEncoder ? ` (forced ${config.forceEncoder})` : ""} → ${ffmpegPath}`,
    );
    let t0 = Date.now();
    try {
      const res = await runExportNativeToPath(
        {
          segments: tl.segments,
          imageUrls: tl.imageUrls,
          audioTrack: tl.audioTrack,
          settings: { ...tl.settings, gpuExportEngine: false },
          kenBurns: tl.kenBurns,
          totalMs: tl.totalMs,
          audio: {
            normalize: false,
            masterVolume: 0.8,
            fadeInMs: 0,
            fadeOutMs: 0,
            musicVolume: 0.5,
            musicStartMs: 0,
            musicLoop: true,
          },
          onProgress: progressLogger("ffmpeg"),
        },
        ffmpegPath,
      );
      runs.push(runResultOf("ffmpeg-smart", `FFmpeg${config.forceEncoder ? ` (forced ${config.forceEncoder})` : ""}`, Date.now() - t0, res));
    } catch (e) {
      runs.push({
        engine: "ffmpeg-smart",
        label: "FFmpeg",
        ok: false,
        wallMs: Date.now() - t0,
        error: e instanceof Error ? e.message : String(e),
      });
    }
    try {
      await api.cleanupTemp();
    } catch {
      /* temp cleanup is best-effort between runs */
    }
    try {
      await api.setForceEncoder(null); // restore the auto-probe
    } catch {
      /* non-fatal */
    }

    // ── Run 2: the WebCodecs GPU engine, inside its dedicated worker. ────
    console.info(`[bench] run 2/2: WebCodecs GPU (worker) → ${gpuPath}`);
    t0 = Date.now();
    try {
      const res = await runExportNativeToPath(
        {
          segments: tl.segments,
          imageUrls: tl.imageUrls,
          audioTrack: tl.audioTrack,
          settings: { ...tl.settings, gpuExportEngine: true },
          kenBurns: tl.kenBurns,
          totalMs: tl.totalMs,
          audio: {
            normalize: false,
            masterVolume: 0.8,
            fadeInMs: 0,
            fadeOutMs: 0,
            musicVolume: 0.5,
            musicStartMs: 0,
            musicLoop: true,
          },
          onProgress: progressLogger("gpu"),
        },
        gpuPath,
      );
      runs.push(runResultOf("webcodecs-gpu", "WebCodecs GPU (worker)", Date.now() - t0, res));
    } catch (e) {
      runs.push({
        engine: "webcodecs-gpu",
        label: "WebCodecs GPU (worker)",
        ok: false,
        wallMs: Date.now() - t0,
        error: e instanceof Error ? e.message : String(e),
      });
    }
  } finally {
    tl.revoke();
  }

  const ok = runs.length > 0 && runs.every((r) => r.ok);
  await api.benchResult({
    ok,
    appVersion,
    platform,
    startedAt: new Date().toISOString(),
    runs,
    notes:
      "Fixture: 1 Ken-Burns image + N H.264 clips (hard cuts) + looping background music. Headless/VM software runs prove nothing about NVENC/QSV/AMF ASIC speed — run on real GPU hardware.",
  });
}

/**
 * Install the bench:run listener (no-op outside Electron with the bench
 * channels present). Returns an uninstall function for React effects.
 */
export function installBenchExportListener(): () => void {
  const api = benchApi();
  if (!api) return () => undefined;
  console.info("[bench] export bench listener installed (FRAMEFUSE_BENCH mode)");
  const off = api.onBenchRun((payload) => {
    void runBench(payload).catch((e) => {
      console.error("[bench] bench run crashed:", e);
      void api.benchResult({
        ok: false,
        appVersion: "unknown",
        platform: "unknown",
        startedAt: new Date().toISOString(),
        runs: [],
        error: e instanceof Error ? e.message : String(e),
      });
    });
  });
  return off;
}
