// src/lib/merger/kinetic/presets.ts — the 24-preset typography library
// (directive §7: five families, real motion-design systems — not positions).
//
// Every preset is a full spec: typography hierarchy + composition rules +
// segmentation targets + entrance/emphasis/hold/exit choreography + visual
// treatment + compatibility metadata. Mirrored (subset) in
// electron/kinetic-ass.js — keep in sync.
//
// Zero imports (pure data).

import type { KineticPresetSpec } from "./types";

// Shared base — each preset overrides what defines its identity.
const B = {
  serifAccent: false,
  marginXFrac: 0.06,
  maxWidthFrac: 0.88,
  blockRotateDeg: 0,
  sideGapFrac: 0.18,
  staggerMs: 110,
  overshoot: 0.12,
  exit: "fade" as const,
  exitMs: 300,
  outline: false,
  shadow: true,
  supportAlpha: 0.78,
  autoWeight: 1,
  fullScreen: false,
};

export const KINETIC_PRESETS: KineticPresetSpec[] = [
  // ══════════════ FAMILY A — CINEMATIC (restrained, editorial) ═════════════

  {
    ...B,
    id: "editorial-stack",
    name: "Editorial Stack",
    family: "cinematic",
    description:
      "Asymmetric editorial hierarchy — large opening phrase, smaller supporting lines, mixed weights.",
    fontId: "inter",
    baseWeight: 500,
    emphasisWeight: 800,
    baseSizeFrac: 0.052,
    emphasisScale: 1.0,
    supportScale: 0.62,
    lineHeightFrac: 1.3,
    trackingFrac: 0.01,
    casing: "none",
    hierarchy: "first-primary",
    anchorY: "center",
    marginYFrac: 0.0,
    preferredWords: [5, 12],
    maxWords: 14,
    maxChars: 70,
    entrance: "fade-rise",
    entranceMs: 340,
    emphasisMotion: "hold",
    hold: "drift",
    accentColor: "#FBBF24",
    intensityRange: [10, 60],
    classificationBias: ["NORMAL_NARRATION", "SETUP", "REFLECTION", "EMOTIONAL"],
    autoWeight: 1.4,
  },
  {
    ...B,
    id: "cinematic-stack",
    name: "Cinematic Stack",
    family: "cinematic",
    description:
      "Large condensed uppercase with subtle scale drift — documentary narrative progression.",
    fontId: "bebas",
    baseWeight: 400,
    emphasisWeight: 400,
    baseSizeFrac: 0.058,
    emphasisScale: 1.0,
    supportScale: 0.84,
    lineHeightFrac: 1.14,
    trackingFrac: 0.04,
    casing: "upper",
    hierarchy: "uniform",
    anchorY: "bottom",
    marginYFrac: 0.12,
    preferredWords: [5, 11],
    maxWords: 13,
    maxChars: 64,
    entrance: "blur-focus",
    entranceMs: 420,
    emphasisMotion: "hold",
    hold: "drift",
    accentColor: "#FCD34D",
    intensityRange: [10, 55],
    classificationBias: ["SETUP", "REFLECTION", "TRANSITION", "NORMAL_NARRATION"],
    autoWeight: 1.2,
  },
  {
    ...B,
    id: "perspective-stack",
    name: "Perspective Stack",
    family: "cinematic",
    description:
      "Spatial depth — phrases scale progressively toward the viewer. Memory, realization, key moments.",
    fontId: "montserrat",
    baseWeight: 600,
    emphasisWeight: 800,
    baseSizeFrac: 0.046,
    emphasisScale: 1.22,
    supportScale: 0.7,
    lineHeightFrac: 1.26,
    trackingFrac: 0.0,
    casing: "none",
    hierarchy: "depth",
    anchorY: "center",
    marginYFrac: 0.0,
    preferredWords: [4, 10],
    maxWords: 12,
    maxChars: 60,
    entrance: "slide-y",
    entranceMs: 380,
    staggerMs: 150,
    emphasisMotion: "scale-punch",
    hold: "none",
    accentColor: "#67E8F9",
    intensityRange: [25, 70],
    classificationBias: ["REALIZATION", "SUSPENSE", "REVELATION"],
    autoWeight: 1.0,
  },
  {
    ...B,
    id: "whisper-type",
    name: "Whisper Type",
    family: "cinematic",
    description:
      "Small, restrained, lowercase — intimate narration, quiet reflection, emotional scenes.",
    fontId: "playfair",
    baseWeight: 400,
    emphasisWeight: 500,
    baseSizeFrac: 0.034,
    emphasisScale: 1.12,
    supportScale: 0.94,
    lineHeightFrac: 1.42,
    trackingFrac: 0.06,
    casing: "none",
    serifAccent: true,
    hierarchy: "center-band",
    anchorY: "bottom",
    marginYFrac: 0.14,
    preferredWords: [6, 12],
    maxWords: 14,
    maxChars: 70,
    entrance: "fade-rise",
    entranceMs: 480,
    staggerMs: 90,
    emphasisMotion: "hold",
    hold: "drift",
    accentColor: "#FDE68A",
    outline: false,
    supportAlpha: 0.66,
    intensityRange: [0, 35],
    classificationBias: ["EMOTIONAL", "REFLECTION"],
    autoWeight: 0.9,
  },
  {
    ...B,
    id: "progressive-stack",
    name: "Progressive Stack",
    family: "cinematic",
    description:
      "The sentence builds phrase by phrase — each step larger. Escalating realization.",
    fontId: "montserrat",
    baseWeight: 600,
    emphasisWeight: 800,
    baseSizeFrac: 0.04,
    emphasisScale: 1.15,
    supportScale: 0.72,
    lineHeightFrac: 1.28,
    trackingFrac: 0.0,
    casing: "none",
    hierarchy: "progressive",
    anchorY: "center",
    marginYFrac: 0.0,
    preferredWords: [5, 11],
    maxWords: 12,
    maxChars: 62,
    entrance: "word-pop",
    entranceMs: 260,
    staggerMs: 140,
    emphasisMotion: "scale-punch",
    hold: "active-word",
    accentColor: "#A5B4FC",
    intensityRange: [20, 70],
    classificationBias: ["REALIZATION", "SUSPENSE", "NORMAL_NARRATION"],
    autoWeight: 1.1,
  },

  // ══════════════ FAMILY B — DRAMATIC (impact moments) ═════════════════════

  {
    ...B,
    id: "punch-stack",
    name: "Punch Stack",
    family: "dramatic",
    description:
      "Large stacked type with ONE dominant keyword — accusations, emotional statements, drama.",
    fontId: "montserrat",
    baseWeight: 700,
    emphasisWeight: 900,
    baseSizeFrac: 0.05,
    emphasisScale: 1.85,
    supportScale: 0.72,
    lineHeightFrac: 1.2,
    trackingFrac: 0.0,
    casing: "upper",
    hierarchy: "emphasis-primary",
    anchorY: "center",
    marginYFrac: 0.0,
    preferredWords: [4, 9],
    maxWords: 10,
    maxChars: 52,
    entrance: "scale-slam",
    entranceMs: 220,
    staggerMs: 130,
    overshoot: 0.22,
    emphasisMotion: "shake",
    hold: "active-accent",
    accentColor: "#F87171",
    intensityRange: [55, 100],
    classificationBias: ["ACCUSATION", "CONFLICT", "SHOCK", "CLIMAX"],
    autoWeight: 1.0,
  },
  {
    ...B,
    id: "impact-word",
    name: "Impact Word",
    family: "dramatic",
    description:
      "One major keyword occupies the frame; support words whisper around it. Revelations.",
    fontId: "arial-black",
    baseWeight: 400,
    emphasisWeight: 900,
    baseSizeFrac: 0.042,
    emphasisScale: 2.6,
    supportScale: 0.5,
    lineHeightFrac: 1.18,
    trackingFrac: -0.01,
    casing: "upper",
    hierarchy: "impact",
    anchorY: "center",
    marginYFrac: 0.0,
    preferredWords: [2, 7],
    maxWords: 8,
    maxChars: 40,
    entrance: "scale-slam",
    entranceMs: 200,
    staggerMs: 110,
    overshoot: 0.25,
    emphasisMotion: "scale-punch",
    hold: "pulse",
    accentColor: "#FACC15",
    intensityRange: [65, 100],
    classificationBias: ["REVELATION", "SHOCK", "CLIMAX", "REALIZATION"],
    autoWeight: 0.9,
  },
  {
    ...B,
    id: "highlight-stack",
    name: "Highlight Stack",
    family: "dramatic",
    description:
      "Readable narration with one dominant keyword in accent color. Facts, revelations, emphasis.",
    fontId: "inter",
    baseWeight: 600,
    emphasisWeight: 900,
    baseSizeFrac: 0.048,
    emphasisScale: 1.42,
    supportScale: 0.88,
    lineHeightFrac: 1.3,
    trackingFrac: 0.0,
    casing: "none",
    hierarchy: "emphasis-primary",
    anchorY: "bottom",
    marginYFrac: 0.13,
    preferredWords: [5, 12],
    maxWords: 13,
    maxChars: 68,
    entrance: "fade-rise",
    entranceMs: 300,
    emphasisMotion: "scale-punch",
    hold: "active-accent",
    accentColor: "#FACC15",
    intensityRange: [35, 80],
    classificationBias: ["REVELATION", "REALIZATION", "NORMAL_NARRATION", "SETUP"],
    autoWeight: 1.3,
  },
  {
    ...B,
    id: "fullscreen-type",
    name: "Full Screen Type",
    family: "dramatic",
    description:
      "Typography becomes the primary visual element — climax and major turning points only.",
    fontId: "bebas",
    baseWeight: 400,
    emphasisWeight: 400,
    baseSizeFrac: 0.085,
    emphasisScale: 1.35,
    supportScale: 0.6,
    lineHeightFrac: 1.08,
    trackingFrac: 0.03,
    casing: "upper",
    hierarchy: "impact",
    anchorY: "center",
    marginYFrac: 0.0,
    preferredWords: [2, 6],
    maxWords: 7,
    maxChars: 34,
    entrance: "flash",
    entranceMs: 140,
    staggerMs: 70,
    emphasisMotion: "scale-punch",
    hold: "pulse",
    accentColor: "#FACC15",
    intensityRange: [80, 100],
    classificationBias: ["CLIMAX", "SHOCK"],
    autoWeight: 0.55,
    fullScreen: true,
  },
  {
    ...B,
    id: "build-collapse",
    name: "Build & Collapse",
    family: "dramatic",
    description:
      "Phrases build progressively, then the whole composition contracts out. Emotional escalation.",
    fontId: "montserrat",
    baseWeight: 700,
    emphasisWeight: 900,
    baseSizeFrac: 0.044,
    emphasisScale: 1.28,
    supportScale: 0.74,
    lineHeightFrac: 1.22,
    trackingFrac: 0.0,
    casing: "none",
    hierarchy: "progressive",
    anchorY: "center",
    marginYFrac: 0.0,
    preferredWords: [4, 10],
    maxWords: 11,
    maxChars: 56,
    entrance: "word-pop",
    entranceMs: 240,
    staggerMs: 150,
    emphasisMotion: "scale-punch",
    hold: "pulse",
    exit: "collapse",
    exitMs: 380,
    accentColor: "#FB923C",
    intensityRange: [50, 90],
    classificationBias: ["CLIMAX", "REALIZATION", "EMOTIONAL"],
    autoWeight: 0.8,
  },

  // ══════════════ FAMILY C — CONFLICT (spatial opposition) ═════════════════

  {
    ...B,
    id: "split-stack",
    name: "Split Stack",
    family: "conflict",
    description:
      "Semantic groups separated spatially — left vs right, entering from opposite directions.",
    fontId: "montserrat",
    baseWeight: 700,
    emphasisWeight: 800,
    baseSizeFrac: 0.046,
    emphasisScale: 1.15,
    supportScale: 0.85,
    lineHeightFrac: 1.26,
    trackingFrac: 0.0,
    casing: "none",
    hierarchy: "split-sides",
    anchorY: "center",
    marginYFrac: 0.0,
    preferredWords: [4, 10],
    maxWords: 12,
    maxChars: 56,
    entrance: "slide-x",
    entranceMs: 340,
    staggerMs: 160,
    emphasisMotion: "hold",
    hold: "active-word",
    accentColor: "#F87171",
    intensityRange: [40, 85],
    classificationBias: ["CONFLICT", "ACCUSATION", "TRANSITION"],
    autoWeight: 1.0,
  },
  {
    ...B,
    id: "type-collision",
    name: "Type Collision",
    family: "conflict",
    description:
      "Two text groups move toward one another and collide. Betrayal, confrontation, conflict.",
    fontId: "arial-black",
    baseWeight: 400,
    emphasisWeight: 900,
    baseSizeFrac: 0.048,
    emphasisScale: 1.3,
    supportScale: 0.8,
    lineHeightFrac: 1.18,
    trackingFrac: 0.0,
    casing: "upper",
    hierarchy: "split-sides",
    anchorY: "center",
    marginYFrac: 0.0,
    preferredWords: [3, 8],
    maxWords: 9,
    maxChars: 44,
    entrance: "converge",
    entranceMs: 300,
    staggerMs: 60,
    overshoot: 0.18,
    emphasisMotion: "shake",
    hold: "none",
    accentColor: "#F87171",
    intensityRange: [60, 100],
    classificationBias: ["CONFLICT", "SHOCK", "ACCUSATION"],
    autoWeight: 0.7,
  },
  {
    ...B,
    id: "push-stack",
    name: "Push Stack",
    family: "conflict",
    description:
      "New phrases push previous ones out of the composition — escalating arguments, discoveries.",
    fontId: "inter",
    baseWeight: 600,
    emphasisWeight: 800,
    baseSizeFrac: 0.05,
    emphasisScale: 1.2,
    supportScale: 0.86,
    lineHeightFrac: 1.28,
    trackingFrac: 0.0,
    casing: "none",
    hierarchy: "last-primary",
    anchorY: "center",
    marginYFrac: 0.0,
    preferredWords: [4, 10],
    maxWords: 11,
    maxChars: 54,
    entrance: "push",
    entranceMs: 280,
    staggerMs: 0,
    emphasisMotion: "scale-punch",
    hold: "active-word",
    exit: "push-out",
    exitMs: 320,
    accentColor: "#67E8F9",
    intensityRange: [35, 80],
    classificationBias: ["CONFLICT", "REVELATION", "SUSPENSE"],
    autoWeight: 0.85,
  },
  {
    ...B,
    id: "opposing-stack",
    name: "Opposing Stack",
    family: "conflict",
    description:
      "Two semantic groups occupy opposite corners — contrast, before/after, truth vs assumption.",
    fontId: "montserrat",
    baseWeight: 600,
    emphasisWeight: 800,
    baseSizeFrac: 0.044,
    emphasisScale: 1.18,
    supportScale: 0.8,
    lineHeightFrac: 1.3,
    trackingFrac: 0.0,
    casing: "none",
    hierarchy: "opposing",
    anchorY: "center",
    marginYFrac: 0.0,
    preferredWords: [4, 10],
    maxWords: 12,
    maxChars: 56,
    entrance: "slide-y",
    entranceMs: 360,
    staggerMs: 170,
    emphasisMotion: "hold",
    hold: "active-word",
    accentColor: "#A5B4FC",
    intensityRange: [30, 75],
    classificationBias: ["CONFLICT", "TRANSITION", "NORMAL_NARRATION"],
    autoWeight: 0.9,
  },
  {
    ...B,
    id: "diagonal-stack",
    name: "Diagonal Stack",
    family: "conflict",
    description:
      "Controlled diagonal composition — phrases step down the frame at a fixed angle.",
    fontId: "bebas",
    baseWeight: 400,
    emphasisWeight: 400,
    baseSizeFrac: 0.052,
    emphasisScale: 1.15,
    supportScale: 0.88,
    lineHeightFrac: 1.12,
    trackingFrac: 0.03,
    casing: "upper",
    hierarchy: "diagonal",
    anchorY: "center",
    marginYFrac: 0.0,
    preferredWords: [4, 10],
    maxWords: 11,
    maxChars: 54,
    entrance: "slide-x",
    entranceMs: 300,
    staggerMs: 130,
    emphasisMotion: "hold",
    hold: "drift",
    accentColor: "#FCD34D",
    blockRotateDeg: -3,
    intensityRange: [25, 70],
    classificationBias: ["SUSPENSE", "TRANSITION", "NORMAL_NARRATION"],
    autoWeight: 0.95,
  },

  // ══════════════ FAMILY D — CONVERSATIONAL (readable flow) ════════════════

  {
    ...B,
    id: "kinetic-sentence",
    name: "Kinetic Sentence",
    family: "conversational",
    description:
      "The sentence stays readable while semantic phrases animate individually. Default narration.",
    fontId: "inter",
    baseWeight: 600,
    emphasisWeight: 800,
    baseSizeFrac: 0.05,
    emphasisScale: 1.12,
    supportScale: 0.96,
    lineHeightFrac: 1.32,
    trackingFrac: 0.0,
    casing: "none",
    hierarchy: "center-band",
    anchorY: "bottom",
    marginYFrac: 0.13,
    preferredWords: [6, 12],
    maxWords: 14,
    maxChars: 70,
    entrance: "fade-rise",
    entranceMs: 280,
    staggerMs: 120,
    emphasisMotion: "scale-punch",
    hold: "active-accent",
    accentColor: "#4ADE80",
    intensityRange: [15, 65],
    classificationBias: ["NORMAL_NARRATION", "SETUP", "EMOTIONAL", "TRANSITION"],
    autoWeight: 1.35,
  },
  {
    ...B,
    id: "word-cascade",
    name: "Word Cascade",
    family: "conversational",
    description:
      "Words enter sequentially with alternating offsets — flowing, rhythmic narration.",
    fontId: "montserrat",
    baseWeight: 600,
    emphasisWeight: 800,
    baseSizeFrac: 0.046,
    emphasisScale: 1.25,
    supportScale: 0.9,
    lineHeightFrac: 1.3,
    trackingFrac: 0.0,
    casing: "none",
    hierarchy: "center-band",
    anchorY: "bottom",
    marginYFrac: 0.12,
    preferredWords: [5, 11],
    maxWords: 12,
    maxChars: 62,
    entrance: "burst",
    entranceMs: 240,
    staggerMs: 90,
    emphasisMotion: "scale-punch",
    hold: "active-word",
    accentColor: "#FDE047",
    intensityRange: [25, 75],
    classificationBias: ["TRANSITION", "SUSPENSE", "NORMAL_NARRATION"],
    autoWeight: 1.0,
  },
  {
    ...B,
    id: "mixed-weight",
    name: "Mixed Weight",
    family: "conversational",
    description:
      "Multiple weights inside one sentence — the emphasized phrase carries the frame.",
    fontId: "inter",
    baseWeight: 400,
    emphasisWeight: 900,
    baseSizeFrac: 0.05,
    emphasisScale: 1.08,
    supportScale: 0.95,
    lineHeightFrac: 1.3,
    trackingFrac: 0.0,
    casing: "none",
    hierarchy: "uniform",
    anchorY: "bottom",
    marginYFrac: 0.13,
    preferredWords: [6, 12],
    maxWords: 14,
    maxChars: 70,
    entrance: "fade-rise",
    entranceMs: 260,
    staggerMs: 70,
    emphasisMotion: "hold",
    hold: "active-word",
    accentColor: "#FBBF24",
    intensityRange: [15, 60],
    classificationBias: ["NORMAL_NARRATION", "SETUP", "REFLECTION"],
    autoWeight: 1.2,
  },
  {
    ...B,
    id: "sliding-sentence",
    name: "Sliding Sentence",
    family: "conversational",
    description:
      "Semantic phrases slide into position sequentially from alternating directions.",
    fontId: "segoe",
    baseWeight: 600,
    emphasisWeight: 800,
    baseSizeFrac: 0.048,
    emphasisScale: 1.16,
    supportScale: 0.92,
    lineHeightFrac: 1.32,
    trackingFrac: 0.0,
    casing: "none",
    hierarchy: "center-band",
    anchorY: "bottom",
    marginYFrac: 0.12,
    preferredWords: [5, 11],
    maxWords: 12,
    maxChars: 64,
    entrance: "slide-x",
    entranceMs: 320,
    staggerMs: 140,
    emphasisMotion: "scale-punch",
    hold: "drift",
    accentColor: "#FBBF24",
    intensityRange: [20, 65],
    classificationBias: ["TRANSITION", "SETUP", "NORMAL_NARRATION"],
    autoWeight: 1.05,
  },
  {
    ...B,
    id: "phrase-reveal",
    name: "Phrase Reveal",
    family: "conversational",
    description:
      "Phrase groups revealed by controlled left-to-right wipes — masks, not motion.",
    fontId: "roboto",
    baseWeight: 600,
    emphasisWeight: 800,
    baseSizeFrac: 0.048,
    emphasisScale: 1.18,
    supportScale: 0.9,
    lineHeightFrac: 1.3,
    trackingFrac: 0.0,
    casing: "none",
    hierarchy: "center-band",
    anchorY: "bottom",
    marginYFrac: 0.12,
    preferredWords: [5, 11],
    maxWords: 12,
    maxChars: 64,
    entrance: "clip-wipe",
    entranceMs: 360,
    staggerMs: 150,
    emphasisMotion: "hold",
    hold: "active-accent",
    accentColor: "#34D399",
    intensityRange: [15, 60],
    classificationBias: ["SUSPENSE", "NORMAL_NARRATION", "SETUP"],
    autoWeight: 1.0,
  },

  // ══════════════ FAMILY E — HIGH INTENSITY (sparingly) ════════════════════

  {
    ...B,
    id: "word-burst",
    name: "Word Burst",
    family: "intensity",
    description:
      "Words enter from multiple controlled directions — high-energy moments only.",
    fontId: "montserrat",
    baseWeight: 800,
    emphasisWeight: 900,
    baseSizeFrac: 0.05,
    emphasisScale: 1.5,
    supportScale: 0.9,
    lineHeightFrac: 1.2,
    trackingFrac: 0.0,
    casing: "upper",
    hierarchy: "emphasis-primary",
    anchorY: "center",
    marginYFrac: 0.0,
    preferredWords: [3, 8],
    maxWords: 9,
    maxChars: 44,
    entrance: "burst",
    entranceMs: 200,
    staggerMs: 70,
    overshoot: 0.2,
    emphasisMotion: "shake",
    hold: "active-accent",
    accentColor: "#F0ABFC",
    intensityRange: [60, 100],
    classificationBias: ["SHOCK", "CLIMAX", "CONFLICT"],
    autoWeight: 0.6,
  },
  {
    ...B,
    id: "collision",
    name: "Collision",
    family: "intensity",
    description:
      "Words move toward a common anchor and converge — impact of accumulating facts.",
    fontId: "arial-black",
    baseWeight: 400,
    emphasisWeight: 900,
    baseSizeFrac: 0.048,
    emphasisScale: 1.42,
    supportScale: 0.85,
    lineHeightFrac: 1.16,
    trackingFrac: 0.0,
    casing: "upper",
    hierarchy: "uniform",
    anchorY: "center",
    marginYFrac: 0.0,
    preferredWords: [3, 8],
    maxWords: 9,
    maxChars: 42,
    entrance: "converge",
    entranceMs: 260,
    staggerMs: 80,
    overshoot: 0.16,
    emphasisMotion: "scale-punch",
    hold: "none",
    accentColor: "#FACC15",
    intensityRange: [55, 100],
    classificationBias: ["SHOCK", "REVELATION", "CLIMAX"],
    autoWeight: 0.6,
  },
  {
    ...B,
    id: "rapid-stack",
    name: "Rapid Stack",
    family: "intensity",
    description:
      "Fast sequential typography — machine-gun pacing for high-energy sequences.",
    fontId: "bebas",
    baseWeight: 400,
    emphasisWeight: 400,
    baseSizeFrac: 0.06,
    emphasisScale: 1.3,
    supportScale: 0.86,
    lineHeightFrac: 1.1,
    trackingFrac: 0.02,
    casing: "upper",
    hierarchy: "uniform",
    anchorY: "center",
    marginYFrac: 0.0,
    preferredWords: [3, 7],
    maxWords: 8,
    maxChars: 38,
    entrance: "typewriter",
    entranceMs: 90,
    staggerMs: 60,
    emphasisMotion: "scale-punch",
    hold: "active-accent",
    exit: "scale-out",
    exitMs: 180,
    accentColor: "#22D3EE",
    intensityRange: [55, 95],
    classificationBias: ["SHOCK", "CLIMAX", "SUSPENSE"],
    autoWeight: 0.6,
  },
  {
    ...B,
    id: "fullscreen-impact",
    name: "Full Screen Impact",
    family: "intensity",
    description:
      "Very large single keyword — the maximum kinetic event. Use sparingly.",
    fontId: "impact",
    baseWeight: 400,
    emphasisWeight: 400,
    baseSizeFrac: 0.11,
    emphasisScale: 1.2,
    supportScale: 0.42,
    lineHeightFrac: 1.0,
    trackingFrac: 0.0,
    casing: "upper",
    hierarchy: "impact",
    anchorY: "center",
    marginYFrac: 0.0,
    preferredWords: [1, 5],
    maxWords: 6,
    maxChars: 30,
    entrance: "flash",
    entranceMs: 110,
    staggerMs: 55,
    overshoot: 0.3,
    emphasisMotion: "shake",
    hold: "pulse",
    exit: "scale-out",
    exitMs: 220,
    accentColor: "#FACC15",
    intensityRange: [85, 100],
    classificationBias: ["CLIMAX", "SHOCK"],
    autoWeight: 0.4,
    fullScreen: true,
  },
];

const BY_ID = new Map(KINETIC_PRESETS.map((p) => [p.id, p]));

export function getKineticPreset(id: string): KineticPresetSpec {
  return BY_ID.get(id) ?? BY_ID.get("editorial-stack")!;
}

export function kineticPresetExists(id: string): boolean {
  return BY_ID.has(id);
}

export const KINETIC_FAMILY_LABELS: Record<string, string> = {
  cinematic: "Cinematic",
  dramatic: "Dramatic",
  conflict: "Conflict",
  conversational: "Conversational",
  intensity: "High Intensity",
};

/** semanticMatch mapping (§15): classification → preferred preset ids. */
export const CLASSIFICATION_PRESETS: Record<string, string[]> = {
  NORMAL_NARRATION: ["kinetic-sentence", "editorial-stack", "mixed-weight"],
  SETUP: ["editorial-stack", "cinematic-stack", "kinetic-sentence"],
  SUSPENSE: ["progressive-stack", "word-cascade", "phrase-reveal"],
  REVELATION: ["highlight-stack", "impact-word", "phrase-reveal"],
  SHOCK: ["impact-word", "word-burst", "rapid-stack"],
  CONFLICT: ["split-stack", "type-collision", "push-stack"],
  ACCUSATION: ["punch-stack", "split-stack", "type-collision"],
  REALIZATION: ["progressive-stack", "highlight-stack", "perspective-stack"],
  EMOTIONAL: ["whisper-type", "editorial-stack", "kinetic-sentence"],
  REFLECTION: ["cinematic-stack", "editorial-stack", "whisper-type"],
  TRANSITION: ["word-cascade", "sliding-sentence", "diagonal-stack"],
  CLIMAX: ["fullscreen-type", "impact-word", "build-collapse"],
};
